export {
  MAX_PRESETS,
  DEFAULT_PRESETS,
  DEFAULT_TIMER_SHORTCUTS,
  compactPresets,
  compactPresetShortcuts,
  createDefaultTimerShortcuts,
  reassignShortcut,
  fastForwardToRemaining,
  sanitizePresetMinutes,
  DEBUG_FAST_FORWARD_SECONDS,
  DEFAULT_PRESET_MINUTES,
  createIdleTimer,
  startTimer,
  stopTimer,
  computeElapsedMs,
  isExpired,
  formatClock,
  formatPresetLabel,
} from "./timer";
export type { TimerState, TimerStatus, StopResult, TimerShortcuts, PresetKeymapEntry, ShortcutTarget } from "./timer";
